version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  inciniprone:
    depends_on: 
      postgres:
        condition: service_healthy
    build: .
    command: ./inciprone
    environment:
      - DB_HOSTNAME=postgres
      - APP_HOSTNAME=0.0.0.0
      - APP_PORT=8080
    ports:
      - 8080:8080

networks:
  default:
    name: incidentprone